import { describe, expect, it } from "vitest";
import {
  duplicateVersions,
  parseBunLock,
  parseNpmLock,
  parsePnpmLock,
  parseYarnLock,
} from "../deps/lockfiles";

describe("lockfile parsers", () => {
  it("parses pnpm v9 keys including scoped names and peer suffixes", () => {
    const text = `
lockfileVersion: '9.0'
packages:
  '@scope/pkg@1.2.3':
    resolution: {integrity: sha512-x}
  'left-pad@1.3.0':
    resolution: {integrity: sha512-y}
  'react-dom@18.2.0(react@18.2.0)':
    resolution: {integrity: sha512-z}
`;
    expect(parsePnpmLock(text)).toEqual([
      { name: "@scope/pkg", version: "1.2.3" },
      { name: "left-pad", version: "1.3.0" },
      { name: "react-dom", version: "18.2.0" },
    ]);
  });

  it("parses pnpm v5 slash keys", () => {
    const text = `
lockfileVersion: 5.4
packages:
  /@babel/core/7.20.0:
    resolution: {integrity: sha512-x}
  /lodash/4.17.21:
    resolution: {integrity: sha512-y}
`;
    expect(parsePnpmLock(text)).toEqual([
      { name: "@babel/core", version: "7.20.0" },
      { name: "lodash", version: "4.17.21" },
    ]);
  });

  it("parses npm lockfile v3 and skips workspace links", () => {
    const text = JSON.stringify({
      lockfileVersion: 3,
      packages: {
        "": { name: "root" },
        "packages/a": { name: "a", version: "1.0.0" },
        "node_modules/a": { resolved: "packages/a", link: true },
        "node_modules/lodash": { version: "4.17.21" },
        "node_modules/x/node_modules/lodash": { version: "3.10.1" },
        "node_modules/@types/node": { version: "20.0.0" },
      },
    });
    expect(parseNpmLock(text)).toEqual([
      { name: "lodash", version: "4.17.21" },
      { name: "lodash", version: "3.10.1" },
      { name: "@types/node", version: "20.0.0" },
    ]);
  });

  it("parses yarn v1 and dedupes identical resolutions", () => {
    const text = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@types/node@^20.0.0", "@types/node@>=18":
  version "20.11.0"
  resolved "https://registry.yarnpkg.com/@types/node/-/node-20.11.0.tgz"

lodash@^4.17.0:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
`;
    expect(parseYarnLock(text)).toEqual([
      { name: "@types/node", version: "20.11.0" },
      { name: "lodash", version: "4.17.21" },
    ]);
  });

  it("parses yarn berry and skips workspaces", () => {
    const text = `# This file is generated by running "yarn install" inside your project.

__metadata:
  version: 8

"lodash@npm:^4.17.0":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"

"my-app@workspace:.":
  version: 0.0.0-use.local
  resolution: "my-app@workspace:."
`;
    expect(parseYarnLock(text)).toEqual([{ name: "lodash", version: "4.17.21" }]);
  });

  it("parses bun.lock text format", () => {
    const text = `{
  "lockfileVersion": 1,
  "packages": {
    "lodash": ["lodash@4.17.21", "", {}, "sha512-x"],
    "@scope/pkg": ["@scope/pkg@2.0.0", "", {}, "sha512-y"],
  },
}`;
    expect(parseBunLock(text)).toEqual([
      { name: "lodash", version: "4.17.21" },
      { name: "@scope/pkg", version: "2.0.0" },
    ]);
  });

  it("finds duplicate versions", () => {
    expect(
      duplicateVersions([
        { name: "a", version: "1.0.0" },
        { name: "a", version: "2.0.0" },
        { name: "b", version: "1.0.0" },
      ]),
    ).toEqual([{ name: "a", versions: ["1.0.0", "2.0.0"] }]);
  });
});
